import { Asset } from "expo-asset";

export const AppImages = {
  search: require("./Home/search.png"),

  dummy_HairWash: require("./Explore/hairWash.jpg"),
  dummy_topBooking1: require("./Explore/topbooking1.png"),
  dummy_topBooking2: require("./Explore/topbooking2.png"),
  dummy_topBooking3: require("./Explore/topbooking3.png"),

  dummy_favourite1: require("./Explore/favourite1.png"),
  dummy_favourite2: require("./Explore/favourite2.png"),
  dummy_favourite3: require("./Explore/favourite3.png"),
  dummy_favourite4: require("./Explore/favourite4.png"),

  homeShop: require("./Home/tab/homeShop.png"),
  homeMore: require("./Home/tab/homeMore.png"),
  homeProCart: require("./Home/tab/homeProCart.png"),
  home: require("./Home/tab/home.png"),
  homeMessage: require("./Home/tab/homeMessage.png"),
  homeExplore: require("./Home/tab/homeExplore.png"),

  category: Asset.fromModule(require("./ProProfile/category.png")).uri,
  proProfileBackground: require("./ProProfile/background.png"),
  signinBackground: Asset.fromModule(require("./Signin/background.png")).uri,
  userTypeBackground: Asset.fromModule(require("./Usertype/background.png"))
    .uri,
  onboardingBackground: Asset.fromModule(require("./Onboarding/background.png"))
    .uri,
  onboardingTeamLogo: require("./Onboarding/teamlogo.png"),

  homeBackground: Asset.fromModule(require("./Home/background.png")).uri,
  filter: require("./Explore/filter.png"),
  dummyProfileImage: require("./Explore/dummyProfileImage.png"),
  addUser: require("./Explore/addUser.png"),
  videoThumbnail: require("./Explore/videoThumbnail.png"),
  playRound: require("./Explore/playRound.png"),
  dummyProductImage: require("./Explore/dummyProductImage.png"),

  close: require("./common/close.png"),
  dummyProfileAvatar: require("./Home/Ellipse.png"),
  searchRedAvatar: require("./Share/searchRedAvatar.png"),

  whatsApp: require("./Share/whatsapp.png"),
  twitter: require("./Share/twitter.png"),
  facebook: require("./Share/facebook.png"),
  instagram: require("./Share/instagram.png"),
  yahoo: require("./Share/yahoo.png"),
  messageApp: require("./Share/messageApp.png"),
  wechat: require("./Share/wechat.png"),
  slack: require("./Share/slack.png"),

  reportRedAvatar: require("./Share/reportRedAvatar.png"),
  duetRedAvatar: require("./Share/duetRedAvatar.png"),
  favouriteRedAvatar: require("./Share/favouriteRedAvatar.png"),
  saveVideoRedAvatar: require("./Share/saveVideoRedAvatar.png"),
  moreCircle: require("./common/moreCircle.png"),
  heartWhite: require("./common/heartWhite.png"),
  heartRed: require("./common/heartRed.png"),
  smiley: require("./Comment/smiley.png"),
  commentSend: require("./Comment/commentSend.png"),
  proBrandAndStyles: require("./Home/pro/proBrandAndStyles.jpg"),
  proProducts: require("./Home/pro/proProducts.jpg"),
  proServices: require("./Home/pro/proServices.jpg"),
  verified: require("./common/verified.png"),
  totalEngagement: require("./Dashboard/totalEngagement.png"),
  totalOrders: require("./Dashboard/totalOrders.png"),
  totalSales: require("./Dashboard/totalSales.png"),
  calendar: require("./common/calendar.png"),
  searchShine: require("./common/searchShine.png"),
  videoEffects: require("./AddService/videoEffects.png"),
  upload: require("./AddService/upload.png"),
  music: require("./common/music.png"),
  addServiceCamera: require("./AddService/addServiceCamera.png"),
  addServiceCut: require("./AddService/addServiceCut.png"),
  addServiceEdit: require("./AddService/addServiceEdit.png"),
  addServiceFlame: require("./AddService/addServiceFlame.png"),
  shopifyAvatar: require("./AddService/shopifyAvatar.png"),
  amazonAvatar: require("./AddService/amazonAvatar.png"),
  user: require("./common/user.png"),
  location: require("./common/location.png"),
  lock: require("./common/lock.png"),
  chatBubble: require("./common/chatBubble.png"),
  multiUsers: require("./common/multiUsers.png"),
  note: require("./common/note.png"),
  send: require("./common/send.png"),
  settingsProfile: require("./Settings/profile.png"),
  settingsPayment: require("./Settings/payment.png"),
  settingsOrder: require("./Settings/orderHistory.png"),
  settingsLogout: require("./Settings/logout.png"),
  settingsMessage: require("./Settings/mail.png"),
  settingsSetting: require("./Settings/setting.png"),
  settingsStore: require("./Settings/store.png"),
  edit: require("./common/edit.png"),
  team: require("./common/team.png"),
  celebrate: require("./common/celebrate.png"),
  multipleUsers: require("./Onboarding/multipleUsers.png"),
  customService: require("./Onboarding/customService.png"),
  verifyingEmployee: require("./Onboarding/verifyingEmployee.png"),
  photoUploadFrame: require("./Onboarding/photoUploadFrame.png"),
  camera: require("./common/camera.png"),

  apple: require("./Settings/apple.png"),
  cards: require("./Settings/cards.png"),
  mastercard: require("./Settings/mastercard.png"),
  stripe: require("./Settings/stripe.png"),
  security: require("./Settings/security.png"),
  apptheme: require("./Settings/apptheme.png"),

  settingsTermPrivacy: require("./Settings/termprivacy.png"),
  settingsLanguage: require("./Settings/language.png"),
  settingsAboutBeauty: require("./Settings/aboutbeauty.png"),
  shoppingBag: require("./common/shoppingBag.png"),
  bagchecked: require("./common/bagchecked.png"),
  augustCreative: require("./augustCreative.png"),
  userAvatar: require("./common/userAvatar.png"),
  video: require("./common/video.png"),
  call: require("./common/call.png"),
  gallery: require("./common/gallery.png"),
  serviceBg: require("./Home/service.jpeg"),
};

export const AppSvgs = {
  search: Asset.fromModule(require("./Home/svg/search.svg")).uri,
  heart: Asset.fromModule(require("./Home/svg/iconlyboldheart.svg")).uri,
  chat: Asset.fromModule(require("./Home/svg/iconlyboldchat.svg")).uri,
  bookmark: Asset.fromModule(require("./Home/svg/iconlyboldbookmark.svg")).uri,
  share: Asset.fromModule(
    require("./Home/svg/categoriesshare-forward-componentadditional-icons.svg"),
  ).uri,
  arrow: Asset.fromModule(require("./common/arrow.svg")).uri,
  unionbg: Asset.fromModule(require("./Home/svg/unionbg.svg")).uri,
  calendarPlus: Asset.fromModule(require("./Home/svg/calendarPlus.svg")).uri,
  video_camera_back: Asset.fromModule(
    require("./Home/svg/video_camera_back.svg"),
  ).uri,
  video_camera_front: Asset.fromModule(
    require("./Home/svg/video_camera_front.svg"),
  ).uri,
  heart1: Asset.fromModule(require("./Home/svg/heart.svg")).uri,
  search1: Asset.fromModule(require("./Home/svg/search1.svg")).uri,
  arrowRight: Asset.fromModule(require("./Home/svg/arrowRight.svg")).uri,
  prosEdit: Asset.fromModule(require("./Home/svg/prosEdit.svg")).uri,
  Delete: Asset.fromModule(require("./Home/svg/Delete.svg")).uri,
  camera: Asset.fromModule(require("./Home/svg/camera.svg")).uri,
  filters: Asset.fromModule(require("./Home/svg/filters.svg")).uri,
};
